### ISSUE TITLE
Forking/Pickling issue when worker.start() is called?!

### ISSUE THREAD

**Issue by JuMaD** [ralph-group/pymeasure#109] opened 2017-08-25 16:30 UTC
Using the ManagedWindow class, I can add experiments to the queue. However, once they should "start" (i.e. the next() method is used) the whole .py file gets interpreted again instead.

In the debugger I traced it down to a new thread being started when the worker is started. When Manager.next._worker.start() is called). Due to the error message below my best guess is, that it has something to do with the forking/pickling issue(s). Since I have no clue about multi-threading, I hope someone can help me fix this. 

![image](https://user-images.githubusercontent.com/13823675/29722901-df3fba50-89c2-11e7-9f97-4c32b699a961.png)

**Comment by cjermain** [comment] 2017-08-25 21:08
@JuMaD, thanks for reporting this issue!

Can you provide more context? Which OS are you using? Are you running one of the examples?

**Comment by JuMaD** [comment] 2017-08-26 11:35
I'm working on Windows 7/10. The problem quite literally popped-up in an own program, but I tested it with the ManagedWindow example (which has a typo in the docs btw ;) ) where it is also an issue.

**Comment by cjermain** [comment] 2017-08-27 19:55
Which version of PyMeasure are you running? Version 0.4.5 had some regressions concerning the Worker behavior that we didn't catch before the release.

**Comment by JuMaD** [comment] 2017-08-28 08:24
I'm running the latest version with some minor adjustments (just expanded the GUI of ManagedWindow with a list to pick an instrument and starting the queue only on Button click [Disabled start_on_add and connected the button to "resume"]).

Everything else is running just fine. But as I said: When I debug, I can see that "starting" the worker leads to a new thread instead.

**Comment by bilderbuchi** [comment] 2017-08-28 09:59
It's probably helpful for the maintainers if you paste the code in question, or a minimum reproducible example and the output you get, here instead of making them search the changes you could mean. ;-)

**Comment by JuMaD** [comment] 2017-08-28 11:30
Ok then. Here's the (adjusted) example from the docs

`
print('Running')
class RandomProcedure(Procedure):
    iterations = IntegerParameter('Loop Iterations')
    delay = FloatParameter('Delay Time', units='s', default=0.2)
    seed = Parameter('Random Seed', default='12345')

    DATA_COLUMNS = ['Iteration', 'Random Number']

    def startup(self):
        log.info("Setting the seed of the random number generator")
        random.seed(self.seed)

    def execute(self):
        log.info("Starting the loop of %d iterations" % self.iterations)
        for i in range(self.iterations):
            data = {
                'Iteration': i,
                'Random Number': random.random()
            }
            self.emit('results', data)
            log.debug("Emitting results: %s" % data)
            sleep(self.delay)
            if self.should_stop():
                log.warning("Caught the stop flag in the procedure")
                break


class MainWindow(ManagedWindow):
    def __init__(self):
        super(MainWindow, self).__init__(
            procedure_class=RandomProcedure,
            inputs=['iterations', 'delay', 'seed'],
            displays=['iterations', 'delay', 'seed'],
            x_axis='Iteration',
            y_axis='Random Number'
        )
        self.setWindowTitle('GUI Example')

    def queue(self):
        filename = 'test.csv'

        procedure = self.make_procedure()
        results = Results(procedure, filename)
        experiment = self.new_experiment(results)

        self.manager.queue(experiment)`

And my edited ManagedWindow class:
`class ManagedWindow(QtGui.QMainWindow):
    """ The ManagedWindow uses a Manager to control Workers in a Queue,
    and provides a simple interface. The queue method must be overwritten
    by a child class which is required to pass an Experiment containing the
    Results and Procedure to self.manager.queue.
    """
    EDITOR = 'gedit'

    def __init__(self, procedure_class, inputs=(), displays=(), x_axis=None, y_axis=None,
                 log_channel='', log_level=logging.INFO, parent=None):
        super().__init__(parent)
        app = QtCore.QCoreApplication.instance()
        app.aboutToQuit.connect(self.quit)
        self.procedure_class = procedure_class
        self.inputs = inputs
        self.displays = displays
        self.log = logging.getLogger(log_channel)
        self.log_level = log_level
        log.setLevel(log_level)
        self.log.setLevel(log_level)
        self.x_axis, self.y_axis = x_axis, y_axis
        self._setup_ui()
        self._layout()


    def _setup_ui(self):
        self.list_widget = QListWidget()
        self.list_widget.itemClicked.connect(self.instrument_clicked)
        self.refresh_button = QtGui.QPushButton('Refresh', self)
        self.refresh_button.setEnabled(True)
        self.refresh_button.clicked.connect(self.refresh_instruments)
        self.refresh_instruments()

        self.log_widget = LogWidget()
        self.log.addHandler(self.log_widget.handler)  # needs to be in Qt context?
        log.info("ManagedWindow connected to logging")
        self.queue_button = QtGui.QPushButton('Queue', self)
        self.queue_button.clicked.connect(self.queue)

        self.abort_button = QtGui.QPushButton('Abort', self)
        self.abort_button.setEnabled(False)
        self.abort_button.clicked.connect(self.abort)

        self.plot_widget = PlotWidget(self.procedure_class.DATA_COLUMNS, self.x_axis, self.y_axis)
        self.plot = self.plot_widget.plot

        self.browser_widget = BrowserWidget(
            self.procedure_class,
            self.displays,
            [self.x_axis, self.y_axis],
            parent=self
        )
        self.browser_widget.show_button.clicked.connect(self.show_experiments)
        self.browser_widget.hide_button.clicked.connect(self.hide_experiments)
        self.browser_widget.clear_button.clicked.connect(self.clear_experiments)
        self.browser_widget.open_button.clicked.connect(self.open_experiment)
        self.browser = self.browser_widget.browser

        self.browser.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.browser.customContextMenuRequested.connect(self.browser_item_menu)
        self.browser.itemChanged.connect(self.browser_item_changed)

        self.inputs = InputsWidget(
            self.procedure_class,
            self.inputs,
            parent=self
        )

        self.manager = Manager(self.plot, self.browser, log_level=self.log_level, parent=self)
        self.manager.abort_returned.connect(self.abort_returned)
        self.manager.queued.connect(self.queued)
        self.manager.running.connect(self.running)
        self.manager.finished.connect(self.finished)
        self.manager.log.connect(self.log.handle)

    def _layout(self):
        self.main = QtGui.QWidget(self)

        inputs_dock = QtGui.QWidget(self)
        inputs_vbox = QtGui.QVBoxLayout(self.main)

        hbox = QtGui.QHBoxLayout()
        hbox.setSpacing(10)
        hbox.setContentsMargins(-1, 6, -1, 6)
        hbox.addWidget(self.queue_button)
        hbox.addWidget(self.abort_button)
        hbox.addStretch()

        inputs_vbox.addWidget(self.inputs)
        inputs_vbox.addLayout(hbox)
        inputs_vbox.addWidget(self.list_widget)
        inputs_vbox.addWidget(self.refresh_button)
        inputs_vbox.addStretch()
        inputs_dock.setLayout(inputs_vbox)

        dock = QtGui.QDockWidget('Input Parameters')
        dock.setWidget(inputs_dock)
        dock.setFeatures(QtGui.QDockWidget.NoDockWidgetFeatures)
        self.addDockWidget(QtCore.Qt.LeftDockWidgetArea, dock)

        tabs = QtGui.QTabWidget(self.main)
        tabs.addTab(self.plot_widget, "Results Graph")
        tabs.addTab(self.log_widget, "Experiment Log")

        splitter = QtGui.QSplitter(QtCore.Qt.Vertical)
        splitter.addWidget(tabs)
        splitter.addWidget(self.browser_widget)
        self.plot_widget.setMinimumSize(100, 200)

        vbox = QtGui.QVBoxLayout(self.main)
        vbox.setSpacing(0)
        vbox.addWidget(splitter)

        self.main.setLayout(vbox)
        self.setCentralWidget(self.main)
        self.main.show()
        self.resize(1000, 800)

    def quit(self, evt=None):
        self.close()

    def refresh_instruments(self):
        if self.list_widget.count() == 0:
            startup = True
        else:
            self.list_widget.clear()
            startup = False
        rm = visa.ResourceManager()
        instrs = rm.list_resources()
        for n, instr in enumerate(instrs):
            # trying to catch errors in comunication
            try:
                res = rm.open_resource(instr)
                # try to avoid errors from *idn?
                try:
                    # noinspection PyUnresolvedReferences
                    idn = res.ask('*idn?')[:-1]
                except visa.Error:
                    idn = "Not known"
                finally:
                    res.close()
                    self.list_widget.addItem(str(n)+"-"+str(instr)+"-"+str(idn))
            except visa.VisaIOError as e:
                print(n, ":", instr, ":", "Visa IO Error: check connections")
                print(e)
        rm.close()
        if not startup:
            QMessageBox.information(self, "Refresh", "Instruments refreshed")
        log.info('Connected instruments refreshed.')

    def instrument_clicked(self, item):
        itemtext = item.text()
        n, instr, idn = itemtext.split('-')
        QMessageBox.information(self, "Instrument Selection",
                                "You clicked: \nitem\t\t" + n + "\nadress:\t\t" + instr + "\nidn:\t\t" + idn)  # TODO: Replace this with a function that adds the selected instrument(-adress) to the current procedure

    def browser_item_changed(self, item, column):
        if column == 0:
            state = item.checkState(0)
            experiment = self.manager.experiments.with_browser_item(item)
            if state == 0:
                self.plot.removeItem(experiment.curve)
            else:
                experiment.curve.x = self.plot_widget.plot_frame.x_axis
                experiment.curve.y = self.plot_widget.plot_frame.y_axis
                experiment.curve.update()
                self.plot.addItem(experiment.curve)

    def browser_item_menu(self, position):
        item = self.browser.itemAt(position)

        if item is not None:
            experiment = self.manager.experiments.with_browser_item(item)

            menu = QtGui.QMenu(self)

            # Open
            action_open = QtGui.QAction(menu)
            action_open.setText("Open Data Externally")
            action_open.triggered.connect(
                lambda: self.open_file_externally(experiment.results.data_filename))
            menu.addAction(action_open)

            # Change Color
            action_change_color = QtGui.QAction(menu)
            action_change_color.setText("Change Color")
            action_change_color.triggered.connect(
                lambda: self.change_color(experiment))
            menu.addAction(action_change_color)

            # Remove
            action_remove = QtGui.QAction(menu)
            action_remove.setText("Remove Graph")
            if self.manager.is_running():
                if self.manager.running_experiment() == experiment:  # Experiment running
                    action_remove.setEnabled(False)
            action_remove.triggered.connect(lambda: self.remove_experiment(experiment))
            menu.addAction(action_remove)

            # Use parameters
            action_use = QtGui.QAction(menu)
            action_use.setText("Use These Parameters")
            action_use.triggered.connect(
                lambda: self.set_parameters(experiment.procedure.parameter_objects()))
            menu.addAction(action_use)
            menu.exec_(self.browser.viewport().mapToGlobal(position))

    def remove_experiment(self, experiment):
        reply = QtGui.QMessageBox.question(self, 'Remove Graph',
                                           "Are you sure you want to remove the graph?",
                                           QtGui.QMessageBox.Yes |
                                           QtGui.QMessageBox.No, QtGui.QMessageBox.No)
        if reply == QtGui.QMessageBox.Yes:
            self.manager.remove(experiment)

    def show_experiments(self):
        root = self.browser.invisibleRootItem()
        for i in range(root.childCount()):
            item = root.child(i)
            item.setCheckState(0, QtCore.Qt.Checked)

    def hide_experiments(self):
        root = self.browser.invisibleRootItem()
        for i in range(root.childCount()):
            item = root.child(i)
            item.setCheckState(0, QtCore.Qt.Unchecked)

    def clear_experiments(self):
        self.manager.clear()

    def open_experiment(self):
        dialog = ResultsDialog(self.procedure_class.DATA_COLUMNS, self.x_axis, self.y_axis)
        if dialog.exec_():
            filenames = dialog.selectedFiles()
            for filename in map(str, filenames):
                if filename in self.manager.experiments:
                    QtGui.QMessageBox.warning(self, "Load Error",
                                              "The file %s cannot be opened twice." % os.path.basename(
                                                  filename))
                elif filename == '':
                    return
                else:
                    results = Results.load(filename)
                    experiment = self.new_experiment(results)
                    experiment.curve.update()
                    experiment.browser_item.progressbar.setValue(100.)
                    self.manager.load(experiment)
                    log.info('Opened data file %s' % filename)

    def change_color(self, experiment):
        color = QtGui.QColorDialog.getColor(
            initial=experiment.curve.opts['pen'].color(), parent=self)
        if color.isValid():
            pixelmap = QtGui.QPixmap(24, 24)
            pixelmap.fill(color)
            experiment.browser_item.setIcon(0, QtGui.QIcon(pixelmap))
            experiment.curve.setPen(pg.mkPen(color=color, width=2))

    def open_file_externally(self, filename):
        # TODO: Make this function OS-agnostic
        import subprocess
        proc = subprocess.Popen([self.EDITOR, filename])

    def make_procedure(self):
        if not isinstance(self.inputs, InputsWidget):
            raise Exception("ManagedWindow can not make a Procedure"
                            " without a InputsWidget type")
        return self.inputs.get_procedure()

    def new_curve(self, results, color=None, **kwargs):
        if color is None:
            color = pg.intColor(self.browser.topLevelItemCount() % 8)
        return self.plot_widget.new_curve(results, color=color, **kwargs)

    def new_experiment(self, results, curve=None):
        if curve is None:
            curve = self.new_curve(results)
        browser_item = BrowserItem(results, curve)
        return Experiment(results, curve, browser_item)

    def set_parameters(self, parameters):
        """ This method should be overwritten by the child class. The
        parameters argument is a dictionary of Parameter objects.
        The Parameters should overwrite the GUI values so that a user
        can click "Queue" to capture the same parameters.
        """
        if not isinstance(self.inputs, InputsWidget):
            raise Exception("ManagedWindow can not set parameters"
                            " without a InputsWidget")
        self.inputs.set_parameters(parameters)

    def queue(self):
        """ This method should be overwritten by the child class. The
        self.manager.queue method should be passed an Experiment object
        which contains the Results and Procedure to be run.
        """
        raise Exception("ManagedWindow child class does not implement queue method")

    def abort(self):
        self.abort_button.setEnabled(False)
        self.abort_button.setText("Resume")
        self.abort_button.clicked.disconnect()
        self.abort_button.clicked.connect(self.resume)
        try:
            self.manager.abort()
        except:
            log.error('Failed to abort experiment', exc_info=True)
            self.abort_button.setText("Abort")
            self.abort_button.clicked.disconnect()
            self.abort_button.clicked.connect(self.abort)

    def resume(self):
        self.abort_button.setText("Abort")
        self.abort_button.clicked.disconnect()
        self.abort_button.clicked.connect(self.abort)
        if self.manager.experiments.has_next():
            self.manager.resume()
        else:
            self.abort_button.setEnabled(False)

    def queued(self, experiment):
        self.abort_button.setEnabled(True)
        self.browser_widget.show_button.setEnabled(True)
        self.browser_widget.hide_button.setEnabled(True)
        self.browser_widget.clear_button.setEnabled(True)

    def running(self, experiment):
        self.browser_widget.clear_button.setEnabled(False)

    def abort_returned(self, experiment):
        if self.manager.experiments.has_next():
            self.abort_button.setText("Resume")
            self.abort_button.setEnabled(True)
        else:
            self.browser_widget.clear_button.setEnabled(True)

    def finished(self, experiment):
        if not self.manager.experiments.has_next():
            self.abort_button.setEnabled(False)
            self.browser_widget.clear_button.setEnabled(True)
`

Everything else is the same as in 0.4.6. Starting the worker (i.e. in this example clicking "queue") leads to a re-interpretation of the whole code and a new window in a new thread instead of a running "experiment". What I mean by this is that even 'print('Running')' gets executed a second time.

**Comment by cjermain** [comment] 2017-08-28 16:14
@JuMaD, I understand. The fact that `print('Running')` is called twice is actually expected. When the Worker starts, it produces a spawned process on Windows. This spawned process starts from scratch, so it must re-import everything and re-establish the procedure class. In doing so, it will re-run the code outside of the procedure class when importing it (since it is not hidden behind a `__main__` if clause), just like this occurs the 1st time when you import it in the main process.

I suspect that you are having an error in the spawned process. I would recommend using `tblib` to help diagnose any errors in the new process. You can add the following code to the main `__init__.py` file in pymeasure:

```python
import tblib.pickling_support
tblib.pickling_support.install()
```
This will ensure that your traceback is properly shown.

Overall, this issue seems to stem from the multiprocess behavior. I recently suggested moving back to all threads (#107), which I suspect would fix this issue. In my mind this is another example where the ability to use multiple CPUs with multiple processes is outweighed by the complexity of troubleshooting edge cases like this one.

FYI, try using ``` (three `) for multi-line code in Markdown.

Does that make sense?

**Comment by JuMaD** [comment] 2017-08-28 17:19
@cjermain, thank you for your tips. 

> I suspect that you are having an error in the spawned process. 

--> That is what I suspected, too. My problem is that I basically have no clue about multi - processing / threading whatsoever, i.e. troubleshooting is difficult for me.

Since I get a new ManagedWindow when the worker is called I suspected that even the `if __name__ == __main__` protected statements, namely
```
app = QtGui.QApplication(sys.argv)  
    window = MainWindow()
    window.show()   
    sys.exit(app.exec_())
```
get called again. So I added a `print("inside __main__")` and a `print("outside __main__")` inside and outside the protected area. This is what I get:

```
outside __main__
inside __main__
outside __main__
outside __main__
inside __main__
```
In the debugger I can see that I ended up with three processes: two times "MainThread" and one "Dummy-6". If I understood you correctly, this explains the obove output (first __main__:1xoutside&1x inside, Dummy-6: outside, second __main__: outside&inside)

I copy&pasted the suggested code - do I have to do anything else? Or where do I see the traceback?

**Comment by cjermain** [comment] 2017-08-29 01:26
@JuMaD, this is an interesting problem. I would have expected only 2 processes to be running at a single time. You won't see the traceback unless there is an explicit error. I'll think about this further.

**Comment by JuMaD** [comment] 2017-08-29 11:17
Thank you for the quick reply and the assistance! 

The second "MainThread" is what confused me, too. 
As for the new window: Could it be, that the problem is, that ManagedWindow is calling  QtCore.QCoreApplication.instance() outside the '__main__' protection?

**Comment by cjermain** [comment] 2017-08-31 00:42
Do you have a link to a fork with the changes you made?

**Comment by JuMaD** [comment] 2017-08-31 06:35
Of course: https://github.com/JuMaD/pymeasure

**Comment by JuMaD** [comment] 2017-09-15 12:57
Have you found the time to have a closer look at this issue?

**Comment by cjermain** [comment] 2017-09-16 15:42
@JuMaD, I have not had the opportunity. I will make some time tomorrow to check it out.

**Comment by cjermain** [comment] 2017-09-17 13:02
@JuMaD, this is most likely an issue with spawn. I can not reproduce it on Linux with your branch `extend_managedwindow` -- on Windows it would use spawn to launch the process. I would suggest that I make the multiprocessing to thread switch (#107) instead of debugging further, so that we are no longer using spawn. If that doesn't remove your issue, it should make it much easier to debug.

You mentioned a typo in the docs. Can you make a PR fix?

**Comment by JuMaD** [comment] 2017-09-17 16:22
Thanks a lot for checking it out! And I agree - switching to thread should "solve" the issue on my end (and propably all other windows users)

I think it was just one typo - I'll check it in more detail tomorrow.

**Comment by ndr37** [comment] 2017-09-18 16:29
I'm not sure if this will be helpful, but I encountered this problem in version 4.6 as well on Windows 7 and, as far as I can tell, reverting to version 4.4. (I did not check version 4.5 because there isn't a wheel).

**Comment by JuMaD** [comment] 2017-10-10 09:18
Thanks ndr37! Reverting back to 4.4 fixes the 'new Window' issue. However, I forgot to make a branch after forking and now I have no clue how to push (only) my changes into the branch with version 0.4.4 :(

Is it worth for me to figure out a way to cherry-pick all commits minus the ones that change to multiprocessing or will the multiprocessing to thread switch be done any time soon?

**Comment by cjermain** [comment] 2017-10-10 12:00
@JuMaD, the multiprocessing to thread switch #113 is complete. If you are willing to test it I would greatly appreciate it. I've been meaning to write more unit tests before merging, but it should work correctly as is.

**Comment by JuMaD** [comment] 2017-10-10 12:04
Great! Is it dev/threads?

**Comment by cjermain** [comment] 2017-10-10 17:28
Yes, its in `dev/threads`.

**Comment by dvspirito** [comment] 2017-10-23 07:06
I had the same issue with `Plotter`, after updating to version 0.5.
This https://github.com/dvspirito/pymeasure/commit/b64a83d128055489b430074a95cc4d054ba1e52e fixed it, however I didn't test much (I'm on Win7). I don't know if this fix can have side effects on other classes.

**Comment by cjermain** [comment] 2017-11-13 23:47
@dvspirito, thanks for bringing this up. I left `Plotter` on multiprocessing when I did the switch (forgetting about the Windows-specific bug) -- it should have also been switched over. Feel free to make a PR with your fix and I will merge.

**Comment by bilderbuchi** [comment] 2020-03-06 10:06
I think this has been fixed in the meantime.

**Closed by bilderbuchi** 2020-03-06 10:06 UTC
