### ISSUE TITLE
Connecting to instrument

### ISSUE THREAD

**Issue by jshoup1** [ralph-group/pymeasure#134] opened 2018-04-13 19:43 UTC
I am new to pymeasure. I am having the following issue when trying to connect/call the instrument.
Any help would be wonderful. 
Thanks
![pymeasure issue](https://user-images.githubusercontent.com/38362722/38754828-51ec5d82-3f31-11e8-947e-3dc8f0ec0585.PNG)

**Comment by bilderbuchi** [comment] 2018-04-13 20:16
This check is pretty fragile (as you found out). Better to use, e.g. `pkg_resources.parse_version()` (https://setuptools.readthedocs.io/en/latest/pkg_resources.html#parsing-utilities) to compare versions. Depends on `setuptools`, but pymeasure is using this already, anyway.

**Comment by cjermain** [comment] 2018-04-14 12:35
@jshoup1, thank you for reporting this. This is the same bug as #130. I will push a fix and release a new version to resolve this issue.

**Comment by cjermain** [comment] 2018-04-14 17:25
@jshoup1, please update PyMeasure to version 0.5.1 and let me know if you still have this issue.

**Comment by jshoup1** [comment] 2018-04-16 14:38
Thank you for the quick response. I updated and it is not working.

**Comment by cjermain** [comment] 2018-04-16 16:25
@jshoup1, can you be specific about the error?

**Comment by bilderbuchi** [comment] 2020-03-06 10:19
Let's close this as a duplicate of #130, and continue the discussion there.

**Closed by bilderbuchi** 2020-03-06 10:19 UTC
